; HEADER_BLOCK_START
; generated by GalaxySlicer 1.0.0-alpha3 on 2023-08-11 at 17:06:06
; total layer number: 0
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START
; thumbnail begin 300x300 2288
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAGe0lEQVR4Ae3d227cOBqF0f3o+80104
; MJkO64Ex1ISXStBfx3KZJ1oQ8su4wkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8oP5/AF6p/53tX6
; YBeIltxzTCBTxsOzjduW4jcMBgW8ZFq7kWOYDf2i5MD6zTAFy05Xq09v5bgMu2mwZgCLECltIIFrCY
; kaFqACZrxApYSOOWBSzCR0NgCduEaYQLmGCbOA3AQFvmR6sBGKCZHy23LWCY5uvI/OypaDVua8AJzb
; 3hclsDLrsjWjNua8CHasZEq1+sPfKWBrxccz4WR426bfXEa4BFNedj8dTeVwZYUDPmhvOGcwgWfFPN
; OwMgVsDfvD0CzZwzihUsZkYEmjnECj7UrBtLM1dz/YzAQmbF6k6NWMG319zzgDf3fH+rO/cAFjQzVD
; 2w/uhw5ac1fgywsFmxGvmxsgHI2Fg1uRwn0QK+1IwJ1t51RAs47UoomuPBGTHAh9oWnAb4SM1asRIs
; +GDNs+HpiTM0wMe6M1IjztEAH6uZf5MaeQ7gwzXjQ3XUrHWBb6i57zb1FcECDmvui9TR/YDFNV//tq
; 0Z84e/zbw/Hj4SRmBRzbWPbc0cPfDvxAq+seb6z5hGf5zLjvV/zJNnBG7SjA/VqCjMPhewkO3GaY7p
; 5PMAC9kemGa/TjwHsIjt4dmrD+4NvMD2gnnivMBimuMPegeudTYevXEv4KDm12g018160Htg3ea8Tl
; 4fOGDmwzjzVnJl7Wbet9yBSWbfUJ6+WW07z9MAr7WdmFl7NPtdOe/IcwA32U7OrH06eL3twuuBl9gu
; THPcqLWPnvXKOg3wuO3izNyzA9bYc0bBgpdrnolVDu7Ri+f+k548B3CTp0J1dv+eeN1eHbweMNDTsf
; pLB5xj1BnvfN/ATneH4I7zjDjjE+8d+I03hWrUmUac8cn3D/xD885Y/bBCrAQLbnA1As3834w1z5xR
; rOBFtoHTzNWMO2f/sNfRNYGJtknTzNVk2tnPDjDRHQ9xM0+TbC8ZYJLm3oe5madJtocHmOSph7r5fu
; FqgGm2F0wz113vA5hkVGRGRquZpxl3VqGCGzVjH9Cr630VwpmaMWcFbjDrIV0pWj80/tcaeLWZt4me
; XF8kgC/NitUPTS7HSrSA/2nuicXIaDXARxt5q/o3jdsWMFCzznehGoAbNMIFLEa0gKU0wgUspBEtYD
; Ejo9UATNa4bQGLES1gKc2YaAHconHLAhYjWMBSGh8JgcUIFrCURqyAxTR+ZgUAAAAwS+OPdIGXavZ9
; wbEBeNDZb2c3ADfaBk0jYMBE26RpxAsYqJkXrK/i1QCctD00jXgBB20vmEa8gB2ad0TLR0dglzcFy+
; 0L+K3mXETEC3jE0XD8rAdfPzJeDfBxmmvROruO2xdwyplI/E5zLj7iBexyNA57NdciJF7AL5rjQZi9
; x8h4Ad/MnSFoku3GaYBvpTkegrv2ES3gF83cCGwPTgN8O7NCsD08DXCr5tdvnDdjv1DZjI3BlcicPc
; +/rQVM1py/UTTnjArWjMB08HrAANugac6F60q0euL1Z8LSCWsCB2yTpjmmJ/e4csYrml8/KgOTNPNi
; dTZc240DLGK7eZp9esNZgEU094bqTLRmngFYxPaCafYZvS+wkO1F0/xZB+4HLGJkZEauddfZgUXMjE
; ovrr9HJ68PvEAzL1T/NDsozfz3ADxk9q1n1J7NfneEF7jZE7H6SzM3KM2599QAr/NUqK6cYfb6ggUv
; 9IZYnTnHHXuIFrzMGx7iu/Zv3vF+gROa87erZsyDfGbvu/drgMc154M14mE+u+cVfWBPYJBtwDTv+/
; 7V7zTn3iPwAtug6b7tHo3V2TM0wGvcEa1eWHe0Prw/cFEzL1xX1pqlD+8PXNSMj9YbY/UzsYLFbQ8P
; wCGNWAGLEStgKY1QAQtpxApYTDMuVg3AZI1oAYsZGa0GYLLGbQtYjGgBS2mEC1hII1rAYvxAHlhK47
; YFLEa0gKU0ggUs5mq0AG7VCBawkMZHQmAxblfAUho3K2BRjUgBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8Cf/Aa
; fzvqU6s9L3AAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
M73 P0 R2
;TYPE:Custom
M83 ; use relative distances for extrusion
G90 ; use absolute coordinates
M140 S55 ; set final bed temp
M104 S180 ; set temporary nozzle temp to prevent oozing during homing
M557 X86.0135:153.986 Y112.867:127.133 S25
G29 S2
G29 S0
M104 S220 ; set final nozzle temp
M190 S55 ; wait for bed temp to stabilize
M109 S220 ; wait for nozzle temp to stabilize
;M593 P"mzv" F59
;M572 D0 S0.06
G90
G1 Y10
M400
G1 Z0.6 F720
G92 E0
G1 X50  Y10 E9 F1000 ; intro line
M73 P1 R2
G1 Y11
M400
G1 X100 Y11 E12.5 F1500 ; intro line
G92 E0
M566 X480.00 Y480.00 Z10.00 E1200.00 P1        ; set maximum instantaneous speed changes (mm/min) // same as M205 but with mm/min
M203 X10800.00 Y10800.00 Z1000.00 E3600.00     ; set maximum speeds (mm/min)
M201 X3000.00 Y3000.00 Z100.00 E3600.00        ; set accelerations (mm/s^2)
   
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M204 P1000
M205 X9 Y9
M73 P2 R2
G1 Z.2 F15000
G1 E-.8 F1800
G1 X65.5 Y156 F15000
M73 P3 R2
G1 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X65.5 Y75.5 E5.35012
M572 D0 S0.01; Override pressure advance value
M73 P5 R2
G1 E-.8 F1800
G17
G3 Z.6 I1.195 J.228 P1  F15000
M73 P6 R2
G1 X67.5 Y65 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y65 E.92643
G1 F9000
G1 X127.5 Y65 E1.85286
G1 F1200
G1 X147.5 Y65 E.92643
M572 D0 S0.011; Override pressure advance value
M73 P7 R2
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y68.5 Z.6 F15000
G1 Z.2 F15000
M73 P8 R2
G1 E.8 F1800
G1 F1200
G1 X87.5 Y68.5 E.92643
G1 F9000
G1 X127.5 Y68.5 E1.85286
G1 F1200
G1 X147.5 Y68.5 E.92643
M572 D0 S0.012; Override pressure advance value
M73 P9 R2
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y72 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y72 E.92643
M73 P10 R2
G1 F9000
G1 X127.5 Y72 E1.85286
G1 F1200
G1 X147.5 Y72 E.92643
M572 D0 S0.013; Override pressure advance value
M73 P11 R2
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y75.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y75.5 E.92643
M73 P12 R2
G1 F9000
G1 X127.5 Y75.5 E1.85286
G1 F1200
G1 X147.5 Y75.5 E.92643
M572 D0 S0.014; Override pressure advance value
M73 P13 R2
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y79 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y79 E.92643
M73 P14 R2
G1 F9000
G1 X127.5 Y79 E1.85286
G1 F1200
G1 X147.5 Y79 E.92643
M572 D0 S0.015; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
M73 P15 R2
G1 X67.5 Y82.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y82.5 E.92643
M73 P16 R2
G1 F9000
G1 X127.5 Y82.5 E1.85286
G1 F1200
G1 X147.5 Y82.5 E.92643
M572 D0 S0.016; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y86 Z.6 F15000
M73 P17 R2
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y86 E.92643
G1 F9000
G1 X127.5 Y86 E1.85286
M73 P18 R2
G1 F1200
G1 X147.5 Y86 E.92643
M572 D0 S0.017; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y89.5 Z.6 F15000
M73 P19 R2
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y89.5 E.92643
G1 F9000
G1 X127.5 Y89.5 E1.85286
G1 F1200
G1 X147.5 Y89.5 E.92643
M572 D0 S0.018; Override pressure advance value
M73 P20 R2
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y93 Z.6 F15000
G1 Z.2 F15000
M73 P21 R2
G1 E.8 F1800
G1 F1200
G1 X87.5 Y93 E.92643
G1 F9000
G1 X127.5 Y93 E1.85286
G1 F1200
G1 X147.5 Y93 E.92643
M572 D0 S0.019; Override pressure advance value
M73 P22 R2
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y96.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y96.5 E.92643
M73 P23 R2
G1 F9000
G1 X127.5 Y96.5 E1.85286
G1 F1200
G1 X147.5 Y96.5 E.92643
M572 D0 S0.02; Override pressure advance value
M73 P24 R2
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y100 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y100 E.92643
M73 P25 R2
G1 F9000
G1 X127.5 Y100 E1.85286
G1 F1200
G1 X147.5 Y100 E.92643
M572 D0 S0.021; Override pressure advance value
M73 P26 R2
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y103.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y103.5 E.92643
M73 P27 R2
G1 F9000
G1 X127.5 Y103.5 E1.85286
G1 F1200
G1 X147.5 Y103.5 E.92643
M572 D0 S0.022; Override pressure advance value
M73 P28 R2
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y107 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y107 E.92643
M73 P29 R2
G1 F9000
G1 X127.5 Y107 E1.85286
G1 F1200
G1 X147.5 Y107 E.92643
M572 D0 S0.023; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
M73 P30 R2
G1 X67.5 Y110.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y110.5 E.92643
G1 F9000
G1 X127.5 Y110.5 E1.85286
M73 P31 R2
G1 F1200
G1 X147.5 Y110.5 E.92643
M572 D0 S0.024; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y114 Z.6 F15000
M73 P32 R2
G1 Z.2 F15000
M73 P32 R1
G1 E.8 F1800
G1 F1200
G1 X87.5 Y114 E.92643
G1 F9000
G1 X127.5 Y114 E1.85286
M73 P33 R1
G1 F1200
G1 X147.5 Y114 E.92643
M572 D0 S0.025; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y117.5 Z.6 F15000
M73 P34 R1
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y117.5 E.92643
G1 F9000
G1 X127.5 Y117.5 E1.85286
G1 F1200
G1 X147.5 Y117.5 E.92643
M572 D0 S0.026; Override pressure advance value
M73 P35 R1
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y121 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y121 E.92643
M73 P36 R1
G1 F9000
G1 X127.5 Y121 E1.85286
G1 F1200
G1 X147.5 Y121 E.92643
M572 D0 S0.027; Override pressure advance value
M73 P37 R1
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y124.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y124.5 E.92643
M73 P38 R1
G1 F9000
G1 X127.5 Y124.5 E1.85286
G1 F1200
G1 X147.5 Y124.5 E.92643
M572 D0 S0.028; Override pressure advance value
M73 P39 R1
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y128 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y128 E.92643
M73 P40 R1
G1 F9000
G1 X127.5 Y128 E1.85286
G1 F1200
G1 X147.5 Y128 E.92643
M572 D0 S0.029; Override pressure advance value
M73 P41 R1
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y131.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y131.5 E.92643
M73 P42 R1
G1 F9000
G1 X127.5 Y131.5 E1.85286
G1 F1200
G1 X147.5 Y131.5 E.92643
M572 D0 S0.03; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
M73 P43 R1
G1 X67.5 Y135 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y135 E.92643
G1 F9000
G1 X127.5 Y135 E1.85286
M73 P44 R1
G1 F1200
G1 X147.5 Y135 E.92643
M572 D0 S0.031; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y138.5 Z.6 F15000
M73 P45 R1
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y138.5 E.92643
G1 F9000
G1 X127.5 Y138.5 E1.85286
M73 P46 R1
G1 F1200
G1 X147.5 Y138.5 E.92643
M572 D0 S0.032; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y142 Z.6 F15000
M73 P47 R1
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y142 E.92643
G1 F9000
G1 X127.5 Y142 E1.85286
G1 F1200
G1 X147.5 Y142 E.92643
M572 D0 S0.033; Override pressure advance value
M73 P48 R1
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y145.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y145.5 E.92643
M73 P49 R1
G1 F9000
G1 X127.5 Y145.5 E1.85286
G1 F1200
G1 X147.5 Y145.5 E.92643
M572 D0 S0.034; Override pressure advance value
M73 P50 R1
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y149 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y149 E.92643
M73 P51 R1
G1 F9000
G1 X127.5 Y149 E1.85286
G1 F1200
G1 X147.5 Y149 E.92643
M572 D0 S0.035; Override pressure advance value
M73 P52 R1
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y152.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y152.5 E.92643
M73 P53 R1
G1 F9000
G1 X127.5 Y152.5 E1.85286
G1 F1200
G1 X147.5 Y152.5 E.92643
M572 D0 S0.036; Override pressure advance value
M73 P54 R1
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y156 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y156 E.92643
M73 P55 R1
G1 F9000
G1 X127.5 Y156 E1.85286
G1 F1200
G1 X147.5 Y156 E.92643
M572 D0 S0.037; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
M73 P56 R1
G1 X67.5 Y159.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y159.5 E.92643
G1 F9000
G1 X127.5 Y159.5 E1.85286
M73 P57 R1
G1 F1200
G1 X147.5 Y159.5 E.92643
M572 D0 S0.038; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y163 Z.6 F15000
M73 P58 R1
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y163 E.92643
G1 F9000
G1 X127.5 Y163 E1.85286
M73 P59 R1
G1 F1200
G1 X147.5 Y163 E.92643
M572 D0 S0.039; Override pressure advance value
G1 E-.8 F1800
G17
G3 Z.6 I-.053 J-1.216 P1  F15000
G1 X67.5 Y166.5 Z.6 F15000
M73 P60 R1
G1 Z.2 F15000
G1 E.8 F1800
G1 F1200
G1 X87.5 Y166.5 E.92643
G1 F9000
G1 X127.5 Y166.5 E1.85286
G1 F1200
G1 X147.5 Y166.5 E.92643
M572 D0 S0; Override pressure advance value
M73 P61 R1
G1 F9000
G1 E-.8 F1800
G17
G3 Z.6 I-.041 J-1.216 P1  F15000
G1 X87.5 Y168.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X87.5 Y173.5 E.23112
M73 P62 R1
G1 E-.8 F1800
G17
G3 Z.6 I0 J1.217 P1  F15000
G1 X127.5 Y173.5 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X127.5 Y168.5 E.23112
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I1.187 J.268 P1  F15000
G1 X150.5 Y66.75 Z.6 F15000
M73 P63 R1
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y66.75 E.07269
G1 X152.5 Y62.75 E.14537
G1 X150.5 Y62.75 E.07269
G1 X150.5 Y66.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y62.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y63.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y66.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y66.75 E.07269
G1 X158.5 Y62.75 E.14537
M73 P64 R1
G1 X156.5 Y62.75 E.07269
G1 X156.5 Y66.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.073 J1.215 P1  F15000
G1 X160.5 Y66.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X160.5 Y62.75 E.14537
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.9 J-.819 P1  F15000
G1 X150.5 Y73.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y73.75 E.07269
G1 X152.5 Y69.75 E.14537
G1 X150.5 Y69.75 E.07269
G1 X150.5 Y73.51 E.14537
M73 P65 R1
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y69.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y70.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y73.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y73.75 E.07269
G1 X158.5 Y69.75 E.14537
G1 X156.5 Y69.75 E.07269
G1 X156.5 Y73.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.073 J1.215 P1  F15000
G1 X160.5 Y73.75 Z.6 F15000
G1 Z.2 F15000
M73 P66 R1
G1 E.8 F1800
G1 X160.5 Y69.75 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-1.088 J.544 P1  F15000
M73 P66 R0
G1 X162.5 Y73.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X164.5 Y73.75 E.07269
G1 X164.5 Y71.75 E.07269
G1 X162.5 Y71.75 E.07269
G1 X162.5 Y69.75 E.07269
G1 X164.5 Y69.75 E.07269
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.752 J-.957 P1  F15000
G1 X150.5 Y80.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y80.75 E.07269
G1 X152.5 Y76.75 E.14537
M73 P67 R0
G1 X150.5 Y76.75 E.07269
G1 X150.5 Y80.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y76.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y77.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y80.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y80.75 E.07269
G1 X158.5 Y76.75 E.14537
G1 X156.5 Y76.75 E.07269
G1 X156.5 Y80.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.073 J1.215 P1  F15000
M73 P68 R0
G1 X160.5 Y80.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X160.5 Y76.75 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-1.088 J.544 P1  F15000
G1 X162.5 Y80.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X162.5 Y78.75 E.07269
G1 X164.5 Y78.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.217 J0 P1  F15000
G1 X164.5 Y80.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X164.5 Y76.75 E.14537
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.752 J-.957 P1  F15000
M73 P69 R0
G1 X150.5 Y87.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y87.75 E.07269
G1 X152.5 Y83.75 E.14537
G1 X150.5 Y83.75 E.07269
G1 X150.5 Y87.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y83.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y84.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y87.75 Z.6 F15000
G1 Z.2 F15000
M73 P70 R0
G1 E.8 F1800
G1 X158.5 Y87.75 E.07269
G1 X158.5 Y83.75 E.14537
G1 X156.5 Y83.75 E.07269
G1 X156.5 Y87.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.073 J1.215 P1  F15000
G1 X160.5 Y87.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X160.5 Y83.75 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.861 J.861 P1  F15000
G1 X164.5 Y87.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X162.5 Y87.75 E.07269
G1 X162.5 Y83.75 E.14537
G1 X164.5 Y83.75 E.07269
M73 P71 R0
G1 X164.5 Y85.75 E.07269
G1 X162.5 Y85.75 E.07269
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.73 J-.974 P1  F15000
G1 X150.5 Y94.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y94.75 E.07269
G1 X152.5 Y90.75 E.14537
G1 X150.5 Y90.75 E.07269
G1 X150.5 Y94.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y90.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y91.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
M73 P72 R0
G1 X156.5 Y94.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y94.75 E.07269
G1 X158.5 Y90.75 E.14537
G1 X156.5 Y90.75 E.07269
G1 X156.5 Y94.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.073 J1.215 P1  F15000
G1 X160.5 Y94.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X160.5 Y90.75 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.544 J1.088 P1  F15000
G1 X164.5 Y92.75 Z.6 F15000
G1 Z.2 F15000
M73 P73 R0
G1 E.8 F1800
G1 X162.5 Y92.75 E.07269
G1 X162.5 Y90.75 E.07269
G1 X164.5 Y90.75 E.07269
G1 X164.5 Y94.75 E.14537
G1 X162.5 Y94.75 E.07269
G1 X162.5 Y92.75 E.07269
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.73 J-.974 P1  F15000
G1 X150.5 Y101.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y101.75 E.07269
G1 X152.5 Y97.75 E.14537
G1 X150.5 Y97.75 E.07269
G1 X150.5 Y101.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
M73 P74 R0
G1 X154.5 Y97.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y98.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y101.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y101.75 E.07269
G1 X158.5 Y97.75 E.14537
G1 X156.5 Y97.75 E.07269
G1 X156.5 Y101.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.097 J1.213 P1  F15000
G1 X159.5 Y101.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X161.5 Y101.75 E.07269
G1 X161.5 Y99.75 E.07269
M73 P75 R0
G1 X159.5 Y99.75 E.07269
G1 X159.5 Y97.75 E.07269
G1 X161.5 Y97.75 E.07269
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.861 J-.861 P1  F15000
G1 X150.5 Y108.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y108.75 E.07269
G1 X152.5 Y104.75 E.14537
G1 X150.5 Y104.75 E.07269
G1 X150.5 Y108.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y104.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y105.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
M73 P76 R0
G1 X156.5 Y108.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y108.75 E.07269
G1 X158.5 Y104.75 E.14537
G1 X156.5 Y104.75 E.07269
G1 X156.5 Y108.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.097 J1.213 P1  F15000
G1 X159.5 Y108.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X161.5 Y108.75 E.07269
G1 X161.5 Y106.75 E.07269
G1 X159.5 Y106.75 E.07269
G1 X159.5 Y104.75 E.07269
G1 X161.5 Y104.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.181 J.295 P1  F15000
M73 P77 R0
G1 X162.5 Y108.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X164.5 Y108.75 E.07269
G1 X164.5 Y106.75 E.07269
G1 X162.5 Y106.75 E.07269
G1 X162.5 Y104.75 E.07269
G1 X164.5 Y104.75 E.07269
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.752 J-.957 P1  F15000
G1 X150.5 Y115.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y115.75 E.07269
G1 X152.5 Y111.75 E.14537
G1 X150.5 Y111.75 E.07269
G1 X150.5 Y115.51 E.14537
G1 E-.8 F1800
G17
M73 P78 R0
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y111.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y112.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y115.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y115.75 E.07269
G1 X158.5 Y111.75 E.14537
G1 X156.5 Y111.75 E.07269
G1 X156.5 Y115.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.097 J1.213 P1  F15000
G1 X159.5 Y115.75 Z.6 F15000
G1 Z.2 F15000
M73 P79 R0
G1 E.8 F1800
G1 X161.5 Y115.75 E.07269
G1 X161.5 Y113.75 E.07269
G1 X159.5 Y113.75 E.07269
G1 X159.5 Y111.75 E.07269
G1 X161.5 Y111.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.181 J.295 P1  F15000
G1 X162.5 Y115.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X162.5 Y113.75 E.07269
G1 X164.5 Y113.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.217 J0 P1  F15000
G1 X164.5 Y115.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X164.5 Y111.75 E.14537
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.752 J-.957 P1  F15000
M73 P80 R0
G1 X150.5 Y122.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y122.75 E.07269
G1 X152.5 Y118.75 E.14537
G1 X150.5 Y118.75 E.07269
G1 X150.5 Y122.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y118.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y119.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y122.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
M73 P81 R0
G1 X158.5 Y122.75 E.07269
G1 X158.5 Y118.75 E.14537
G1 X156.5 Y118.75 E.07269
G1 X156.5 Y122.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.097 J1.213 P1  F15000
G1 X159.5 Y122.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X161.5 Y122.75 E.07269
G1 X161.5 Y120.75 E.07269
G1 X159.5 Y120.75 E.07269
G1 X159.5 Y118.75 E.07269
G1 X161.5 Y118.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-.974 J.73 P1  F15000
G1 X164.5 Y122.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X162.5 Y122.75 E.07269
M73 P82 R0
G1 X162.5 Y118.75 E.14537
G1 X164.5 Y118.75 E.07269
G1 X164.5 Y120.75 E.07269
G1 X162.5 Y120.75 E.07269
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.73 J-.974 P1  F15000
G1 X150.5 Y129.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y129.75 E.07269
G1 X152.5 Y125.75 E.14537
G1 X150.5 Y125.75 E.07269
G1 X150.5 Y129.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y125.75 Z.6 F15000
G1 Z.2 F15000
M73 P83 R0
G1 E.8 F1800
G1 X154.5 Y126.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y129.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y129.75 E.07269
G1 X158.5 Y125.75 E.14537
G1 X156.5 Y125.75 E.07269
G1 X156.5 Y129.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.097 J1.213 P1  F15000
G1 X159.5 Y129.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X161.5 Y129.75 E.07269
G1 X161.5 Y127.75 E.07269
G1 X159.5 Y127.75 E.07269
G1 X159.5 Y125.75 E.07269
M73 P84 R0
G1 X161.5 Y125.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-.675 J1.013 P1  F15000
G1 X164.5 Y127.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X162.5 Y127.75 E.07269
G1 X162.5 Y125.75 E.07269
G1 X164.5 Y125.75 E.07269
G1 X164.5 Y129.75 E.14537
G1 X162.5 Y129.75 E.07269
G1 X162.5 Y127.75 E.07269
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.73 J-.974 P1  F15000
G1 X150.5 Y136.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y136.75 E.07269
G1 X152.5 Y132.75 E.14537
M73 P85 R0
G1 X150.5 Y132.75 E.07269
G1 X150.5 Y136.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y132.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y133.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y136.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y136.75 E.07269
G1 X158.5 Y132.75 E.14537
G1 X156.5 Y132.75 E.07269
G1 X156.5 Y136.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.097 J1.213 P1  F15000
M73 P86 R0
G1 X159.5 Y136.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X161.5 Y136.75 E.07269
G1 X161.5 Y132.75 E.14537
G1 X159.5 Y132.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-.914 J.804 P1  F15000
G1 X161.26 Y134.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X159.5 Y134.75 E.07269
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.861 J-.861 P1  F15000
G1 X150.5 Y143.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y143.75 E.07269
G1 X152.5 Y139.75 E.14537
M73 P87 R0
G1 X150.5 Y139.75 E.07269
G1 X150.5 Y143.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y139.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y140.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y143.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y143.75 E.07269
G1 X158.5 Y139.75 E.14537
G1 X156.5 Y139.75 E.07269
G1 X156.5 Y143.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.097 J1.213 P1  F15000
M73 P88 R0
G1 X159.5 Y143.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X161.5 Y143.75 E.07269
G1 X161.5 Y139.75 E.14537
G1 X159.5 Y139.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-.914 J.804 P1  F15000
G1 X161.26 Y141.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X159.5 Y141.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-.675 J1.013 P1  F15000
G1 X162.5 Y143.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X164.5 Y143.75 E.07269
G1 X164.5 Y141.75 E.07269
M73 P89 R0
G1 X162.5 Y141.75 E.07269
G1 X162.5 Y139.75 E.07269
G1 X164.5 Y139.75 E.07269
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.752 J-.957 P1  F15000
G1 X150.5 Y150.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y150.75 E.07269
G1 X152.5 Y146.75 E.14537
G1 X150.5 Y146.75 E.07269
G1 X150.5 Y150.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y146.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y147.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
M73 P90 R0
G1 X156.5 Y150.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y150.75 E.07269
G1 X158.5 Y146.75 E.14537
G1 X156.5 Y146.75 E.07269
G1 X156.5 Y150.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.097 J1.213 P1  F15000
G1 X159.5 Y150.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X161.5 Y150.75 E.07269
G1 X161.5 Y146.75 E.14537
G1 X159.5 Y146.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-.914 J.804 P1  F15000
M73 P91 R0
G1 X161.26 Y148.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X159.5 Y148.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-.675 J1.013 P1  F15000
G1 X162.5 Y150.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X162.5 Y148.75 E.07269
G1 X164.5 Y148.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.217 J0 P1  F15000
G1 X164.5 Y150.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X164.5 Y146.75 E.14537
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.752 J-.957 P1  F15000
G1 X150.5 Y157.75 Z.6 F15000
M73 P92 R0
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y157.75 E.07269
G1 X152.5 Y153.75 E.14537
G1 X150.5 Y153.75 E.07269
G1 X150.5 Y157.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
G1 X154.5 Y153.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y154.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y157.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y157.75 E.07269
G1 X158.5 Y153.75 E.14537
M73 P93 R0
G1 X156.5 Y153.75 E.07269
G1 X156.5 Y157.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.097 J1.213 P1  F15000
G1 X159.5 Y157.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X161.5 Y157.75 E.07269
G1 X161.5 Y153.75 E.14537
G1 X159.5 Y153.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-.914 J.804 P1  F15000
G1 X161.26 Y155.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X159.5 Y155.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-.452 J1.13 P1  F15000
M73 P94 R0
G1 X164.5 Y157.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X162.5 Y157.75 E.07269
G1 X162.5 Y153.75 E.14537
G1 X164.5 Y153.75 E.07269
G1 X164.5 Y155.75 E.07269
G1 X162.5 Y155.75 E.07269
G1 F3600
G1 E-.8 F1800
G17
G3 Z.6 I-.73 J-.974 P1  F15000
G1 X150.5 Y164.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X152.5 Y164.75 E.07269
G1 X152.5 Y160.75 E.14537
G1 X150.5 Y160.75 E.07269
G1 X150.5 Y164.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I.834 J.887 P1  F15000
M73 P95 R0
G1 X154.5 Y160.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X154.5 Y161.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-1.013 J.675 P1  F15000
G1 X156.5 Y164.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X158.5 Y164.75 E.07269
G1 X158.5 Y160.75 E.14537
G1 X156.5 Y160.75 E.07269
G1 X156.5 Y164.51 E.14537
G1 E-.8 F1800
G17
G3 Z.6 I-.097 J1.213 P1  F15000
G1 X159.5 Y164.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X161.5 Y164.75 E.07269
M73 P96 R0
G1 X161.5 Y160.75 E.14537
G1 X159.5 Y160.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I-.914 J.804 P1  F15000
G1 X161.26 Y162.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X159.5 Y162.75 E.07269
G1 E-.8 F1800
G17
G3 Z.6 I0 J1.217 P1  F15000
G1 X164.5 Y162.75 Z.6 F15000
G1 Z.2 F15000
G1 E.8 F1800
G1 X162.5 Y162.75 E.07269
G1 X162.5 Y160.75 E.07269
G1 X164.5 Y160.75 E.07269
G1 X164.5 Y164.75 E.14537
G1 X162.5 Y164.75 E.07269
G1 X162.5 Y162.75 E.07269
M73 P97 R0
G1 E-.8 F1800
M106 S0
;TYPE:Custom
; filament end gcode 
; config end gcode
G4 ; wait
M221 S100 ; reset flow
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30 ; Move print head up
M73 P98 R0
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 139.52
; filament used [cm3] = 0.34
; filament used [g] = 0.42
; filament cost = 0.01; total filament used [g] = 0.42
; total filament cost = 0.01
; total layers count = 1
; estimated printing time (normal mode) = 2m 56s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; additional_cooling_fan_speed = 70
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_temperature_difference = 10
; before_layer_change_gcode = 
; bottom_shell_layers = 4
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 0
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; cool_plate_temp = 35
; cool_plate_temp_initial_layer = 35
; curr_bed_type = High Temp Plate
; default_acceleration = 2500
; default_filament_colour = #000000
; default_filament_profile = "KiS-3d Generic PLA @0.4 nozzle"
; default_jerk = 12
; default_print_profile = 0.20mm Standard @KiS-3d S235EVO (0.4 nozzle)
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = internal_solid_infill_line_width;line_width;outer_wall_line_width;default_filament_colour;filament_max_volumetric_speed;filament_retraction_length;filament_z_hop;filament_z_hop_types;hot_plate_temp;hot_plate_temp_initial_layer;nozzle_temperature;fan_kickstart;fan_speedup_time;host_type;machine_end_gcode;machine_max_acceleration_e;machine_max_acceleration_extruding;machine_max_acceleration_retracting;machine_max_acceleration_x;machine_max_acceleration_y;machine_start_gcode;print_host;z_hop_types
; draft_shield = disabled
; elefant_foot_compensation = 0
; enable_arc_fitting = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = 1
; exclude_object = 1
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 100
; fan_kickstart = 1
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 1
; filament_colour = #000000
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.98
; filament_ids = GFL99
; filament_is_support = 0
; filament_max_volumetric_speed = 18
; filament_minimal_purge_on_wipe_tower = 15
; filament_retraction_length = 0.8
; filament_settings_id = "S235 Generic PLA @0.4"
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_type = PLA
; filament_vendor = Generic
; filament_z_hop = 0.4
; filament_z_hop_types = Auto Lift
; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
; filter_out_gap_fill = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_infill_speed = 40
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = 1
; host_type = duet
; hot_plate_temp = 55
; hot_plate_temp_initial_layer = 55
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @KiS-3d S235EVO (0.4 nozzle)";"KiS-3d Generic PLA @0.4 nozzle";"KiS-3d S235 EVO (0.4 nozzle)"
; initial_layer_acceleration = 1000
; initial_layer_infill_speed = 125
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 1000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 250
; interface_shells = 0
; internal_bridge_support_thickness = 0
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.45
; internal_solid_infill_speed = 200
; ironing_flow = 10%
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.45
; machine_end_gcode = ; config end gcode\nG4 ; wait\nM221 S100 ; reset flow\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors\n
; machine_load_filament_time = 0
; machine_max_acceleration_e = 1000
; machine_max_acceleration_extruding = 9000
; machine_max_acceleration_retracting = 3000
; machine_max_acceleration_travel = 12000
; machine_max_acceleration_x = 9000
; machine_max_acceleration_y = 9000
; machine_max_acceleration_z = 500
; machine_max_jerk_e = 3
; machine_max_jerk_x = 9
; machine_max_jerk_y = 9
; machine_max_jerk_z = 2.5
; machine_max_speed_e = 40
; machine_max_speed_x = 350
; machine_max_speed_y = 350
; machine_max_speed_z = 10
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = 
; machine_start_gcode = M83 ; use relative distances for extrusion\nG90 ; use absolute coordinates\nM140 S[bed_temperature_initial_layer_single] ; set final bed temp\nM104 S180 ; set temporary nozzle temp to prevent oozing during homing\nM557 X{first_layer_print_min[0]}:{first_layer_print_max[0]} Y{first_layer_print_min[1]}:{first_layer_print_max[1]} S25\nG29 S2\nG29 S0\nM104 S[nozzle_temperature_initial_layer] ; set final nozzle temp\nM190 S[bed_temperature_initial_layer_single] ; wait for bed temp to stabilize\nM109 S[nozzle_temperature_initial_layer] ; wait for nozzle temp to stabilize\n;M593 P"mzv" F59\n;M572 D0 S0.06\nG90\nG1 Y10\nM400\nG1 Z0.6 F720\nG92 E0\nG1 X50  Y10 E9 F1000 ; intro line\nG1 Y11\nM400\nG1 X100 Y11 E12.5 F1500 ; intro line\nG92 E0\nM566 X480.00 Y480.00 Z10.00 E1200.00 P1        ; set maximum instantaneous speed changes (mm/min) // same as M205 but with mm/min\nM203 X10800.00 Y10800.00 Z1000.00 E3600.00     ; set maximum speeds (mm/min)\nM201 X3000.00 Y3000.00 Z100.00 E3600.00        ; set accelerations (mm/s^2)\n   
; machine_unload_filament_time = 0
; max_bridge_length = 10
; max_layer_height = 0.3
; max_travel_detour_distance = 0
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; minimum_sparse_infill_area = 15
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 215
; nozzle_temperature_initial_layer = 220
; nozzle_temperature_range_high = 230
; nozzle_temperature_range_low = 190
; nozzle_type = hardened_steel
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; outer_wall_acceleration = 1000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.45
; outer_wall_speed = 150
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_speed_classic = 0
; post_process = 
; precise_outer_wall = 0
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "KiS-3d S235 EVO (0.4 nozzle)"
; print_flow_ratio = 1
; print_host = 192.168.8.170
; print_host_webui = 
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @KiS-3d S235EVO (0.4 nozzle) - Copy
; printable_area = 0x0,235x0,235x235,0x235
; printable_height = 250
; printer_model = KiS-3d S235 EVO
; printer_settings_id = KiS3d S235 EVO (0.4)
; printer_technology = FFF
; printer_variant = 0.4
; printhost_apikey = 
; printhost_authorization_type = key
; printhost_cafile = 
; printhost_password = 
; printhost_port = 
; printhost_ssl_ignore_revoke = 0
; printhost_user = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 80%
; retract_length_toolchange = 2
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_length = 0.8
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; seam_gap = 15%
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 1
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 10
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_speed = 250
; spiral_mode = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_pattern = rectilinear
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.4
; support_material_interface_fan_speed = -1
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_plate_temp = 45
; textured_plate_temp_initial_layer = 45
; thick_bridges = 0
; thumbnails = 300x300
; timelapse_type = 0
; top_shell_layers = 4
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 1500
; top_surface_jerk = 9
; top_surface_line_width = 0.4
; top_surface_pattern = monotonic
; top_surface_speed = 150
; travel_acceleration = 2500
; travel_jerk = 9
; travel_speed = 250
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_auto_brim = 1
; tree_support_branch_angle = 30
; tree_support_branch_diameter = 5
; tree_support_branch_distance = 5
; tree_support_brim_width = 3
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_infill_order = inner wall/outer wall/infill
; wall_loops = 3
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_distance = 2
; wipe_on_loops = 1
; wipe_speed = 80%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 155.000
; wipe_tower_y = 165.000
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; first_layer_bed_temperature = 55
; bed_shape = 0x0,235x0,235x235,0x235
; first_layer_temperature = 220
; first_layer_height = 0.200
; CONFIG_BLOCK_END


